# Generated by Django 2.2 on 2020-05-27 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FABRICA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=200)),
                ('Puerto', models.CharField(max_length=200)),
                ('Nombre', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos_Fabrica',
            fields=[
                ('Codigo_Pedido', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Pedido', models.DateField(auto_now_add=True)),
                ('Fecha_Recepcion', models.DateField()),
                ('Total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('Estado', models.CharField(choices=[('enviado', 'Enviado'), ('proceso', 'Proceso'), ('recibido', 'Recibido')], max_length=50)),
                ('Codigo_Fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fabricas.FABRICA')),
            ],
        ),
        migrations.CreateModel(
            name='Recepcion_Fabrica',
            fields=[
                ('Codigo_RF', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo_Pedido', models.CharField(max_length=200)),
                ('Codigo_ProductoFab', models.IntegerField(default=0)),
                ('Precio_lista', models.IntegerField(default=0)),
                ('Numero_De_Parte', models.IntegerField(default=0)),
                ('Nombre_Producto', models.CharField(max_length=200)),
                ('Fecha_Pedido', models.DateField()),
                ('Fecha_Recepcion', models.DateField()),
                ('Cantidad', models.IntegerField(default=0)),
                ('Precio_Fabricante', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('Total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('Pedido_Fabrica', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Fabricas.Pedidos_Fabrica')),
            ],
        ),
    ]
