# Generated by Django 2.2 on 2020-05-28 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricas', '0002_detalle_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos_fabrica',
            name='Codigo_Fabrica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Fabricas.FABRICA'),
        ),
        migrations.AlterField(
            model_name='pedidos_fabrica',
            name='Estado',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('proceso', 'Proceso'), ('recibido', 'Recibido')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos_fabrica',
            name='Fecha_Recepcion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pedidos_fabrica',
            name='Total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
