# Generated by Django 2.2 on 2020-05-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricas', '0003_auto_20200527_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos_fabrica',
            name='Total',
            field=models.FloatField(null=True),
        ),
    ]
