# Generated by Django 2.2 on 2020-05-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricas', '0004_auto_20200527_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idfk', models.CharField(max_length=200)),
                ('fecha_recibido', models.CharField(max_length=200)),
                ('fecha_entrega', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('repuestos', models.CharField(max_length=200)),
                ('clientes', models.CharField(max_length=200)),
                ('precio_final', models.CharField(max_length=200)),
                ('cantidad', models.CharField(max_length=200)),
            ],
        ),
    ]
