# Generated by Django 2.2 on 2020-05-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricas', '0006_recepcion_fabrica_fabricante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcion_fabrica',
            name='Cantidad',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recepcion_fabrica',
            name='Codigo_Pedido',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recepcion_fabrica',
            name='Codigo_ProductoFab',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recepcion_fabrica',
            name='Fecha_Pedido',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recepcion_fabrica',
            name='Fecha_Recepcion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recepcion_fabrica',
            name='Nombre_Producto',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recepcion_fabrica',
            name='Numero_De_Parte',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recepcion_fabrica',
            name='Precio_Fabricante',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recepcion_fabrica',
            name='Precio_lista',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recepcion_fabrica',
            name='Total',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
