# Generated by Django 2.2 on 2020-05-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricas', '0007_auto_20200530_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcion_fabrica',
            name='Codigo_ProductoFab',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
