# Generated by Django 2.2 on 2020-05-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricas', '0008_auto_20200530_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepcion_fabrica',
            name='Codigo_ProductoFab',
        ),
    ]
