# Generated by Django 2.2 on 2020-05-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fabricas', '0009_remove_recepcion_fabrica_codigo_productofab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepcion_fabrica',
            name='Pedido_Fabrica',
        ),
    ]
