# Generated by Django 2.2 on 2020-05-27 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Fabricas', '0001_initial'),
        ('Cientes', '0001_initial'),
        ('Repuestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Venta',
            fields=[
                ('Tipo_Venta', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID_USUARIO', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Usuario', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Vendedor', 'Vendedor')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('Codigo_Venta', models.AutoField(primary_key=True, serialize=False)),
                ('Fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fabricas.FABRICA')),
                ('Tipo_Venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas.Tipo_Venta')),
            ],
        ),
        migrations.CreateModel(
            name='FACTURA',
            fields=[
                ('Numero_Factura', models.AutoField(primary_key=True, serialize=False)),
                ('Total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('Estado', models.CharField(max_length=200)),
                ('Cliente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Cientes.Clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('Codigo', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(default=0)),
                ('Sub_Total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('Factura', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Ventas.FACTURA')),
                ('Repuesto', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Repuestos.REPUESTOS')),
                ('Venta', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Ventas.Ventas')),
            ],
        ),
    ]
