# Generated by Django 2.2 on 2020-05-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_ventas_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='Tipo_Venta',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Registrado', 'Registrado'), ('Credito', 'Credito'), ('Futuro', 'Futuro')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Tipo_Venta',
        ),
    ]
