# Generated by Django 2.2 on 2020-05-27 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_auto_20200526_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_venta',
            name='Factura',
        ),
        migrations.AddField(
            model_name='factura',
            name='Venta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Ventas.Ventas'),
        ),
    ]
