# Generated by Django 2.2 on 2020-05-27 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0004_auto_20200526_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='Fabricante',
        ),
        migrations.AddField(
            model_name='factura',
            name='Nit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='Nombre_cliente',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Cliente',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='Cientes.Clientes'),
        ),
    ]
