# Generated by Django 2.2 on 2020-05-27 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('ID_TIPO', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('mayorista', 'Mayorista'), ('taller', 'Taller')], max_length=50)),
                ('Descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('ID_CLIENTE', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('nit', models.PositiveIntegerField(unique=True)),
                ('email', models.CharField(max_length=60)),
                ('telefono', models.PositiveIntegerField()),
                ('patente', models.ImageField(upload_to='images/')),
                ('fecha_inicio', models.DateField(default='2020-01-01')),
                ('fecha_fin', models.DateField(default='2020-01-01')),
                ('TIPO_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cientes.Tipo')),
            ],
        ),
    ]
